### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by lybxlpsv** [lybxlpsv/EvenMoreLegitArcadeController#12]
Not in any particular order.

- [x] Implement Xinput
- [ ] Implement ini write
- [ ] Refactor and Move GLComponent into a sane location
- [ ] Tidy up ScaleComponent
- [ ] Make the mouse.cpp input scaling algo more sane
- [ ] Remove duplicate functions
- [ ] Rename variables to be more consistent
- [x] Hook up frame limiter to framerate manager component
- [ ] Fix warnings
